apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsapideployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products-container
        image: ashokit/products
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: productssvc
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: products
  ports:
  - port: 80
    targetPort: 8080
